### ISSUE TITLE
console logger with apex liked colored level encoder

### ISSUE THREAD

**Issue by ttys3** [ttys3/slogsimple#3]
maybe ref https://gist.github.com/ttys3/5d05e5eb8cda55d0795b83b2df78d083

or https://github.com/charmbracelet/log/blob/main/level.go

**Comment by ttys3** [comment]
done via https://github.com/ttys3/sslog/commit/275e46526398c1ab5ed0bc4f3533b63532d73a9d

![image](https://github.com/ttys3/sslog/assets/41882455/3f9b85ff-1403-482a-acfe-a028c7551185)

**Comment by StevenACoffman** [comment]
Nice! Thanks!
